### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by DcNdrew** [SmithsGaming/Armory#43] opened 2016-11-04 14:51 UTC
Hi!

There is an item or something what causes the JEI to crash in Armory mod. It dies when JEI should show it. Without your mod it works perfectly.

Here is the log:
http://paste.ee/p/j4wmP

**Comment by marchermans** [comment] 2016-11-04 15:51
Hello drew,

Two things:
1) Optifine is installed, any bugs with Optifine will not be processed, try the sane setup without optifine. The reason for this is the fact that optifine changes the way Mc renders and in its current base it is hardly compatible with complex model systems. Keeping armories system working with both is impossible.
2) Looking at your crashlog their is nothing indicating armories involvement directly, I see that you are using a newer version then I am in my Dev environment so I will update and check again.

I will you try to reproduce this bug for you, however only if you can reproduce it without optifine.

Greets Orion

**Comment by DcNdrew** [comment] 2016-11-05 11:34
Thanks, I'll try.

**Comment by DcNdrew** [comment] 2016-11-05 12:22
Without Optifine crashes too.
http://paste.ee/p/WXhxi

I start to write armor, and then bamm.
Without Armory there is no crash.

**Comment by marchermans** [comment] 2016-11-07 13:41
Okey I will take a look at it. It seems that EvilCraft is trying to render a Tank with molten metal, but it is not setting the metal type in its NBT. Which causes an NPE to occur,

**Comment by marchermans** [comment] 2017-02-05 18:51
Fixed in an update to 1.11

**Closed as completed by marchermans** 2017-02-05 18:51 UTC
Labels: Bug, Working on it ........, Question
